[package]
name = "activitypub"
version = "0.1.0"
authors = ["Riley Trautman <rileyt@spiceworks.com>"]

[dependencies]
activitystreams-derive = "0.1"
activitystreams-traits = "0.1"
activitystreams-types = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
